### ISSUE TITLE
Problems getting browser settings from the network, {}

### ISSUE THREAD

**Issue by pronebird** [joshuef/beaker#21]
Operation System: OSX latest
Beaker Version: tag 0.4

It says Problems getting browser settings from the network, {}

**Comment by joshuef** [comment]
@pronebird Has it loaded at all? Can you see any logs in the launcher?

Eitherway, could you try with a freshly created account and let me know how you get on.

**Comment by frabrunelle** [comment]
@pronebird which version of SAFE Launcher are you using?

**Comment by pronebird** [comment]
@frabrunelle it's Version 0.8.0 (0.8.0)

**Comment by frabrunelle** [comment]
OK that might be why it doesn't work. Can you please try with [SAFE Launcher v0.10.0](https://github.com/maidsafe/safe_launcher/releases/tag/0.10.0)? (you'll have to create a new account since this is a different network – TEST 11 instead of Alpha 1)

**Comment by pronebird** [comment]
@frabrunelle same issue

https://www.dropbox.com/s/x09t7p30rsd8udx/Screenshot%202016-12-02%2012.04.11.png?dl=0

**Comment by frabrunelle** [comment]
I just remembered that I was also getting this error not long ago. It was recently fixed by @joshuef. Can you please try with [SAFE Browser v0.4.2](https://github.com/joshuef/beaker/releases/tag/v0.4.2)? (I would recommend trying with a new account to make sure it works)

**Comment by pronebird** [comment]
@frabrunelle looking into this. It would be great to have auto-updater though.

**Comment by pronebird** [comment]
it works guys! Thanks!
