### ISSUE TITLE
Can't use DevTools > Application 

### ISSUE THREAD

**Issue by happybeing** [joshuef/beaker#4]
Operation System: Linux
Beaker Version: 0.3.0

Start beaker
Menu > BeakerDev > Toggle Shell-Window DevTools
Click Tab: Application

The beaker window loses everything except the menu bar and I don't see a way to get the location bar back. New Tab etc do nothing.

**Comment by happybeing** [comment]
I'm not sure what the difference is, but I can access the Application storage without the above problem if I use View > Toggle DevTools rather than BeakerDev > Toggle Shell-Window DevTools. So no hold-ups for me as it stands.

**Comment by joshuef** [comment]
There's a 'dev tools' for the whole application and then individual 'dev tools' for each tab. The latter (`View > Toggle DevTools`) is what you should be using for developing a webapp.

This doesn't necessarily solve this one, but just to note for clarity.

**Comment by joshuef** [comment]
As I read this, it was an issue with using the 'beaker' dev tools as opposed to any individual window. Please correct me if I'm wrong, @theWebalyst . 

Otherwise we can close this.

**Comment by happybeing** [comment]
Yes, I hadn't seen the View > DevTools when I raised this. I have no problem closing it, although nuking the UI is still a bug, if only I've for devs :)

**Comment by joshuef** [comment]
Is this happening with the latest builds @theWebalyst ?

I can't replicate on osx right now...

**Comment by happybeing** [comment]
Yes. Doesn't happen when run locally, only with builds - last tested with 0.4.3-1 (on Debian).

**Comment by joshuef** [comment]
Ah right, you mean that the menu option is gone is a bug for you? Fair enough. I could reimplement this and bury it as a sub menu perhaps? Just to avoid unwitting users clicking it... 

Sound reasonable?

**Comment by happybeing** [comment]
No! 

The github issue is the thing - I'm talking about the debugger not working at all. I can start it with Ctrl-Alt-I but it crashes on that site.

**Comment by happybeing** [comment]
Ooops. my comments today were about #15 - my mistake and apologies

**Comment by joshuef** [comment]
@theWebalyst no worries. I'll keep the dev menu in dev only mode for now then until there's a specific need for that in compiled code.
