### ISSUE TITLE
blank window on close of tab

### ISSUE THREAD

**Issue by davidpbrown** [joshuef/beaker#6]
Operation System: Linux
Beaker Version: safe-browser-v0.3.5-linux-x64 (which oddly unzipped this time as "linux-unpacked")

Open two tabs.. close the second and see a big window of white that obscures the first tab even. So, not option from there but to close and restart.

**Comment by joshuef** [comment]
@davidpbrown can you check this with the latest build please and let me know how you get on.

I can't replicate this in OSX as it stands.

**Comment by davidpbrown** [comment]
Sorry..delayed reply. Looks to be fixed. thanks.
