### ISSUE TITLE
url bar does not default to safe:// 

### ISSUE THREAD

**Issue by davidpbrown** [joshuef/beaker#7]
Operation System: Linux
Beaker Version: safe-browser-v0.3.5-linux-x64

urls appear to still require safe:// is typed in the address, rather than just defaulting to that.
Also the list of favorites makes no sense, since they are not accessible as http://

**Comment by joshuef** [comment]
yup. Both on the list 😄 

favourites will come with safeSync, as I'll be overriding this behaviour entirely.

safe:// as a default should be something I can drop in a little sooner, I think.
