### ISSUE TITLE
Cache hiding page updates

### ISSUE THREAD

**Issue by davidpbrown** [joshuef/beaker#8]
Operation System: Linux
Beaker Version: safe-browser-v0.3.5-linux-x64

Could do with switching off the cache for all but app data. The browser strongly prefer the cache without any apparent option to force a refresh.

It would be good to see at least Ctrl or Shift + Refresh force redownload of the full page and related scripts; as it stands, I need to delete the entire cache to check if a page had updated. That doesn't affect add-on comments functions but the static in a page, will be updated from time to time and users might not see those changes, if they've visited a page before.

**Comment by joshuef** [comment]
Actually this exists under view, hard reload. 

This triggers the page to reload ignoring the cache. 

This appears to be functioning normally. It may be that we're missing a linux shortcut for this though.

**Comment by joshuef** [comment]
Actually, it's registered with `Ctrl+Shift+R` for linux: https://github.com/joshuef/beaker/blob/master/app/background-process/ui/window-menu.js#L117

That's what you're looking for I think.
